import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header";
import Footer from "@/components/footer";
import { fontBody, fontHeading } from "./fonts";
import FloatingActions from "@/sections/FloatingActions";
import AOSProvider from "@/components/AOSProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontBody.variable} ${fontHeading.variable} antialiased`}
      >
        <Navbar/>
         <AOSProvider />
        <FloatingActions
          whatsappNumber="919999999999"
          linkedinUrl="https://www.linkedin.com/company/national-engineers/"
          // WhatsappIcon={...} LinkedinIcon={...} EnquiryIcon={...}
        />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
